/**
 * UI-Strings für beide Apps: lengua (es) und llengua (ca).
 * Sprache kommt aus NEXT_PUBLIC_LANG (Build-Zeit, pro Vercel-Projekt gesetzt).
 * Interne Zustands-Werte (sin_ver, flojo, ...) bleiben sprachneutrale Identifier —
 * nur ihre Labels werden übersetzt.
 */

export const LANG = (process.env.NEXT_PUBLIC_LANG ?? "es") as "es" | "ca";

const es = {
  appName: "lengua",
  // nav
  navInicio: "Inicio", navGramatica: "Gramática", navVocabulario: "Vocabulario",
  navPracticar: "Practicar", navCapturar: "Capturar",
  // inicio
  inicioTitle: "Inicio",
  bandHot: "En caliente", bandReview: "Para repasar", bandPrep: "Prep para hoy",
  emptyHot: "Los conceptos recién promovidos aparecerán aquí.",
  emptyReview: "Tu repaso del día, cuando haya vocabulario que repasar.",
  emptyPrep: "Preparación para tus citas de hoy.",
  errorsCaptured: (n: number) => `${n} ${n === 1 ? "fallo" : "fallos"} capturados`,
  wordsToReview: (n: number) => `${n} ${n === 1 ? "palabra" : "palabras"} para repasar`,
  captureHint: "Captura algo de tu día con el botón",
  loadFailed: "(no se pudo cargar — ¿backend corriendo?)",
  loading: "cargando…",
  // capturar
  capturarTitle: "Capturar",
  placeholderDefault: "Lo que dijiste, lo que viste, lo que no entendiste…",
  placeholderVoice: "La voz llega pronto — de momento, escribe lo que oíste…",
  placeholderPhotoContext: "Contexto opcional para la foto…",
  photoReady: "Foto lista para analizar", photoRemove: "Quitar foto",
  cameraBtn: "Cámara", captureBtn: "Capturar", analyzing: "analizando…",
  captureFailed: (e: string) => `No se pudo capturar (${e}). ¿Está corriendo el backend?`,
  modeLabels: { check: "revisado", decode: "descifrado", brief: "preparación", listen: "escuchado" } as Record<string, string>,
  correctMark: "✓ Correcto.",
  savedSilently: "guardado en silencio ✓", seeLesson: "→ ver lección",
  historyTitle: "Últimas capturas",
  timeNow: "ahora", timeMin: (n: number) => `hace ${n} min`,
  timeH: (n: number) => `hace ${n} h`, timeD: (n: number) => `hace ${n} d`,
  packageReady: (v: number, f: number, c: number) =>
    `${v} palabras · ${f} frases · ${c} conceptos activados → ver paquete`,
  photoFallback: "(foto)",
  // gramática
  gramaticaTitle: "Gramática",
  summary: (total: number, touched: number, hot: number, dom: number) =>
    `${total} capítulos · ${touched} tocados · ${hot} en caliente · ${dom} dominados`,
  yoursNow: "Lo tuyo ahora", draft: "borrador", draftLong: "borrador — sin revisar",
  chapterMissing: "Este capítulo no existe.",
  yourProblem: "Esto es lo que te pasa",
  timesCaptured: (n: number) =>
    `${n} ${n === 1 ? "vez" : "veces"} capturado — la regla de abajo explica tu problema.`,
  ruleOfThumb: "Regla de oro", germanPitfall: "⚠️ La trampa alemana",
  paradigm: "Paradigma", patternVerbs: "Verbos de este patrón", tryIt: "Para probar",
  draftEmpty: "Este capítulo nació de tus capturas y aún no tiene contenido.",
  generateBtn: "✨ Generar contenido", generating: "escribiendo el capítulo… (medio minuto)",
  generateFailed: "No se pudo generar — inténtalo otra vez.",
  // vocabulario
  vocabularioTitle: "Vocabulario",
  dueToday: (n: number) => `${n} para repasar hoy → Practicar`,
  allReviewed: "todo repasado por hoy ✓",
  newSituationPlaceholder: "Nueva situación… (p.ej. cita con el dentista)",
  createBtn: "crear", creating: "montando…",
  createFailed: "No se pudo crear — ¿backend corriendo?",
  situationsTitle: "Situaciones", looseTitle: "Sueltas — de tus capturas",
  items: (n: number) => `${n} ${n === 1 ? "elemento" : "elementos"}`,
  seedTag: " · estándar",
  vocabEmpty: "Aún no hay vocabulario — captura algo o crea una situación arriba.",
  briefPrefix: "prepárame para",
  shelfCrumb: "situación", keyVocab: "Vocabulario clave",
  intentPhrases: "Frases con intención", activatedGrammar: "La gramática que esto activa",
  situationMissing: "Esta situación no existe.",
  dictTitle: "Diccionari bàsic",  // nur ca-relevant, es hat kein Seed-Vokabular
  dictAdd: "añadir", dictAdded: "en tu repaso ✓",
  // practicar
  practicarTitle: "Practicar",
  modes: [
    { tipo: "mix", label: "Mix", desc: "Un poco de todo — donde cojeas ahora" },
    { tipo: "palabras", label: "Palabras", desc: "Solo vocabulario (SRS)" },
    { tipo: "frases", label: "Frases", desc: "Frases con intención de tus preps" },
    { tipo: "conjugacion", label: "Conjugación", desc: "Verbo · tiempo · persona → forma" },
  ],
  preparingSession: "preparando sesión…",
  sessionLoadFailed: "No se pudo cargar la sesión — ¿backend corriendo?",
  nothingPending: "Nada pendiente en esta categoría ahora mismo — captura más o prueba otro modo.",
  chooseOther: "← elegir otro modo",
  sessionDone: "Sesión terminada ✓", cardsReviewed: (n: number) => `${n} tarjetas repasadas.`,
  tallyGood: "bien", tallyBad: "mal", anotherSession: "otra sesión", toInicio: "→ Inicio",
  howToSay: "¿Cómo se dice?", howToSayPhrase: "¿Cómo se dice esta frase?",
  fixYourSentence: "Corrige tu frase", conjugate: "Conjuga",
  showBtn: "mostrar", nextBtn: "siguiente",
  // login
  loginHello: "Hola 👋", loginSub: "Entra para seguir aprendiendo.",
  loginUser: "usuario", loginPass: "contraseña", loginBtn: "Entrar", loggingIn: "entrando…",
  loginWrong: "Usuario o contraseña incorrectos.", loginFailed: "Algo falló.",
  loginNoBackend: "No hay conexión con el backend.",
  // nivel
  nivelTitle: "Test de nivel",
  nivelHint: "~3 minutos · si no lo sabes, elige cualquiera — así sabemos dónde empezar.",
  evaluating: "evaluando…", yourLevel: "Tu nivel aproximado",
  correctOf: (c: number, t: number) => `${c} de ${t} correctas.`,
  weakIntro: "Tus primeros puntos flojos — ya están en tu Gramática:",
  startBtn: "Empezar →",
  // perfil
  perfilTitle: "Perfil", logoutBtn: "Salir", levelPrefix: "nivel ~", adminTag: "admin",
  usersTitle: "Usuarios", testPending: "test pendiente", passwordBtn: "contraseña",
  newUserTitle: "Nuevo usuario",
  userPlaceholder: "usuario (solo letras/números)", namePlaceholder: "nombre visible",
  passPlaceholder: "contraseña (mín. 8)",
  userCreated: (u: string) => `Usuario '${u}' creado ✓`,
  passChanged: (u: string) => `Contraseña de '${u}' cambiada ✓`,
  newPassPrompt: (u: string) => `Nueva contraseña para '${u}' (mín. 8):`,
  somethingFailed: "Algo falló.",
  // estados
  stateLabels: {
    sin_ver: "sin ver", visto: "visto", flojo: "flojo",
    aprendiendo: "aprendiendo", dominado: "dominado",
  } as Record<string, string>,
  persons: ["yo", "tu", "el", "nosotros", "vosotros", "ellos"],
  personLabels: {
    yo: "yo", tu: "tú", el: "él/ella", nosotros: "nosotros",
    vosotros: "vosotros", ellos: "ellos/ellas",
  } as Record<string, string>,
};

const ca: typeof es = {
  appName: "llengua",
  navInicio: "Inici", navGramatica: "Gramàtica", navVocabulario: "Vocabulari",
  navPracticar: "Practicar", navCapturar: "Capturar",
  inicioTitle: "Inici",
  bandHot: "En calent", bandReview: "Per repassar", bandPrep: "Prep per avui",
  emptyHot: "Els conceptes acabats de promoure apareixeran aquí.",
  emptyReview: "El teu repàs del dia, quan hi hagi vocabulari per repassar.",
  emptyPrep: "Preparació per a les teves cites d'avui.",
  errorsCaptured: (n) => `${n} ${n === 1 ? "error capturat" : "errors capturats"}`,
  wordsToReview: (n) => `${n} ${n === 1 ? "paraula" : "paraules"} per repassar`,
  captureHint: "Captura alguna cosa del teu dia amb el botó",
  loadFailed: "(no s'ha pogut carregar — el backend funciona?)",
  loading: "carregant…",
  capturarTitle: "Capturar",
  placeholderDefault: "El que has dit, el que has vist, el que no has entès…",
  placeholderVoice: "La veu arriba aviat — de moment, escriu el que has sentit…",
  placeholderPhotoContext: "Context opcional per a la foto…",
  photoReady: "Foto a punt per analitzar", photoRemove: "Treure la foto",
  cameraBtn: "Càmera", captureBtn: "Capturar", analyzing: "analitzant…",
  captureFailed: (e) => `No s'ha pogut capturar (${e}). El backend funciona?`,
  modeLabels: { check: "revisat", decode: "desxifrat", brief: "preparació", listen: "escoltat" },
  correctMark: "✓ Correcte.",
  savedSilently: "desat en silenci ✓", seeLesson: "→ veure la lliçó",
  historyTitle: "Últimes captures",
  timeNow: "ara", timeMin: (n) => `fa ${n} min`,
  timeH: (n) => `fa ${n} h`, timeD: (n) => `fa ${n} d`,
  packageReady: (v, f, c) => `${v} paraules · ${f} frases · ${c} conceptes activats → veure el paquet`,
  photoFallback: "(foto)",
  gramaticaTitle: "Gramàtica",
  summary: (total, touched, hot, dom) =>
    `${total} capítols · ${touched} tocats · ${hot} en calent · ${dom} dominats`,
  yoursNow: "El teu ara mateix", draft: "esborrany", draftLong: "esborrany — sense revisar",
  chapterMissing: "Aquest capítol no existeix.",
  yourProblem: "Això és el que et passa",
  timesCaptured: (n) =>
    `${n} ${n === 1 ? "vegada capturada" : "vegades capturades"} — la regla de sota explica el teu problema.`,
  ruleOfThumb: "Regla d'or", germanPitfall: "⚠️ La trampa alemanya",
  paradigm: "Paradigma", patternVerbs: "Verbs d'aquest patró", tryIt: "Per provar",
  draftEmpty: "Aquest capítol va néixer de les teves captures i encara no té contingut.",
  generateBtn: "✨ Generar contingut", generating: "escrivint el capítol… (mig minut)",
  generateFailed: "No s'ha pogut generar — torna-ho a provar.",
  vocabularioTitle: "Vocabulari",
  dueToday: (n) => `${n} per repassar avui → Practicar`,
  allReviewed: "tot repassat per avui ✓",
  newSituationPlaceholder: "Nova situació… (p. ex. cita amb el dentista)",
  createBtn: "crear", creating: "muntant…",
  createFailed: "No s'ha pogut crear — el backend funciona?",
  situationsTitle: "Situacions", looseTitle: "Soltes — de les teves captures",
  items: (n) => `${n} ${n === 1 ? "element" : "elements"}`,
  seedTag: " · estàndard",
  vocabEmpty: "Encara no hi ha vocabulari — captura alguna cosa o crea una situació a dalt.",
  briefPrefix: "prepara'm per a",
  shelfCrumb: "situació", keyVocab: "Vocabulari clau",
  intentPhrases: "Frases amb intenció", activatedGrammar: "La gramàtica que això activa",
  situationMissing: "Aquesta situació no existeix.",
  dictTitle: "Diccionari bàsic",
  dictAdd: "afegir", dictAdded: "al teu repàs ✓",
  practicarTitle: "Practicar",
  modes: [
    { tipo: "mix", label: "Mix", desc: "Una mica de tot — on falles ara" },
    { tipo: "palabras", label: "Paraules", desc: "Només vocabulari (SRS)" },
    { tipo: "frases", label: "Frases", desc: "Frases amb intenció de les teves preps" },
    { tipo: "conjugacion", label: "Conjugació", desc: "Verb · temps · persona → forma" },
  ],
  preparingSession: "preparant la sessió…",
  sessionLoadFailed: "No s'ha pogut carregar la sessió — el backend funciona?",
  nothingPending: "Res pendent en aquesta categoria ara mateix — captura més o prova un altre mode.",
  chooseOther: "← triar un altre mode",
  sessionDone: "Sessió acabada ✓", cardsReviewed: (n) => `${n} targetes repassades.`,
  tallyGood: "bé", tallyBad: "malament", anotherSession: "una altra sessió", toInicio: "→ Inici",
  howToSay: "Com es diu?", howToSayPhrase: "Com es diu aquesta frase?",
  fixYourSentence: "Corregeix la teva frase", conjugate: "Conjuga",
  showBtn: "mostrar", nextBtn: "següent",
  loginHello: "Hola 👋", loginSub: "Entra per continuar aprenent.",
  loginUser: "usuari", loginPass: "contrasenya", loginBtn: "Entrar", loggingIn: "entrant…",
  loginWrong: "Usuari o contrasenya incorrectes.", loginFailed: "Alguna cosa ha fallat.",
  loginNoBackend: "No hi ha connexió amb el backend.",
  nivelTitle: "Test de nivell",
  nivelHint: "~3 minuts · si no ho saps, tria qualsevol — així sabem on començar.",
  evaluating: "avaluant…", yourLevel: "El teu nivell aproximat",
  correctOf: (c, t) => `${c} de ${t} correctes.`,
  weakIntro: "Els teus primers punts fluixos — ja són a la teva Gramàtica:",
  startBtn: "Començar →",
  perfilTitle: "Perfil", logoutBtn: "Sortir", levelPrefix: "nivell ~", adminTag: "admin",
  usersTitle: "Usuaris", testPending: "test pendent", passwordBtn: "contrasenya",
  newUserTitle: "Nou usuari",
  userPlaceholder: "usuari (només lletres/números)", namePlaceholder: "nom visible",
  passPlaceholder: "contrasenya (mín. 8)",
  userCreated: (u) => `Usuari '${u}' creat ✓`,
  passChanged: (u) => `Contrasenya de '${u}' canviada ✓`,
  newPassPrompt: (u) => `Nova contrasenya per a '${u}' (mín. 8):`,
  somethingFailed: "Alguna cosa ha fallat.",
  stateLabels: {
    sin_ver: "per veure", visto: "vist", flojo: "fluix",
    aprendiendo: "aprenent", dominado: "dominat",
  },
  persons: ["jo", "tu", "ell", "nosaltres", "vosaltres", "ells"],
  personLabels: {
    jo: "jo", tu: "tu", ell: "ell/ella", nosaltres: "nosaltres",
    vosaltres: "vosaltres", ells: "ells/elles",
  },
};

export const S = LANG === "ca" ? ca : es;
