/**
 * UI-Strings für beide Apps: lengua (es) und llengua (ca).
 * Sprache kommt aus NEXT_PUBLIC_LANG (Build-Zeit, pro Vercel-Projekt gesetzt).
 * Interne Zustands-Werte (sin_ver, flojo, ...) bleiben sprachneutrale Identifier —
 * nur ihre Labels werden übersetzt.
 */

export const LANG = (process.env.NEXT_PUBLIC_LANG ?? "es") as "es" | "ca";

const es = {
  appName: "lengua",
  // nav
  navInicio: "Inicio", navGramatica: "Gramática", navVocabulario: "Vocabulario",
  navPracticar: "Practicar", navCapturar: "Capturar", navHablar: "Hablar",
  // hablar (Speaking Bot — ES-only, Tab in BottomNav per LANG gegated)
  hablarTitle: "Hablar",
  hablarEmpty: "Aún no hay sesiones — contesta a las preguntas del bot de Telegram y aparecerán aquí.",
  hablarOpenChunks: "chunks abiertos",
  hablarErrors14d: "fallos · 14 días",
  hablarSessionErrors: (n: number) => `${n} ${n === 1 ? "fallo" : "fallos"}`,
  hablarSessionChunks: (n: number) => `${n} ${n === 1 ? "chunk" : "chunks"}`,
  hablarRecurrence: (n: number) => `${n}ª vez en 14 días`,
  hablarTranscript: "Transcripción",
  hablarCorrected: "Versión corregida",
  hablarErrorsTitle: "Fallos",
  hablarChunksTitle: "Chunks",
  hablarAudioMissing: "Audio no disponible.",
  hablarLegend: "rojo = fallo · ámbar = palabra alemana · punteado = poca confianza",
  // Quelle des Enums: lengua-bot/constants.py ERROR_TYPES + db/migrations/012 — synchron halten.
  errorTypeLabels: {
    subjuntivo: "subjuntivo", ser_estar: "ser/estar",
    indefinido_imperfecto: "indefinido/imperfecto", perifrasis: "perífrasis",
    preposicion: "preposición", concordancia: "concordancia", genero: "género",
    lexico: "léxico", orden_palabras: "orden de palabras", germanismo: "germanismo",
    registro: "registro", conector: "conector",
  } as Record<string, string>,
  chunkStatusLabels: {
    open: "abierto", activated: "activado", dropped: "caducado",
  } as Record<string, string>,
  // inicio
  inicioTitle: "Inicio",
  greetMorning: "Buenos días", greetAfternoon: "Buenas tardes", greetEvening: "Buenas noches",
  inicioGrammar: "Tu gramática ahora", inicioVocab: "Pon a prueba tu vocabulario",
  inicioListen: "Comprensión oral",
  vocabTestCta: "Practica tu vocabulario",
  emptyGrammar: "Aún no hay temas — captura algo y aparecerán.",
  bandHot: "En caliente", bandReview: "Para repasar", bandPrep: "Prep para hoy",
  emptyHot: "Los conceptos recién promovidos aparecerán aquí.",
  emptyReview: "Tu repaso del día, cuando haya vocabulario que repasar.",
  emptyPrep: "Preparación para tus citas de hoy.",
  errorsCaptured: (n: number) => `${n} ${n === 1 ? "fallo capturado" : "fallos capturados"}`,
  wordsToReview: (n: number) => `${n} ${n === 1 ? "palabra" : "palabras"} para repasar`,
  captureHint: "Captura algo de tu día con el botón",
  loadFailed: "(no se pudo cargar — ¿backend corriendo?)",
  loading: "cargando…",
  // capturar
  capturarTitle: "Capturar",
  placeholderDefault: "Lo que dijiste, lo que viste, lo que no entendiste…",
  placeholderVoice: "Graba con 🎤 — o escribe lo que oíste…",
  voiceBtn: "Voz", voiceStop: "Parar", recording: "grabando…",
  audioReady: "Audio listo — se transcribe al capturar", audioRemove: "Quitar audio",
  micDenied: "Sin acceso al micrófono — revisa los permisos.", heard: "escuché:",
  placeholderPhotoContext: "Contexto opcional para la foto…",
  photoReady: "Foto lista para analizar", photoRemove: "Quitar foto",
  cameraBtn: "Cámara", captureBtn: "Capturar", analyzing: "analizando…",
  captureFailed: (e: string) => `No se pudo capturar (${e}). ¿Está corriendo el backend?`,
  modeLabels: { check: "revisado", decode: "descifrado", brief: "preparación", listen: "escuchado", word: "palabra" } as Record<string, string>,
  wordAdded: "→ a tu vocabulario ✓", wordKnown: "ya en tu vocabulario",
  correctMark: "✓ Correcto.",
  savedSilently: "guardado en silencio ✓", seeLesson: "→ ver lección",
  historyTitle: "Últimas capturas",
  timeNow: "ahora", timeMin: (n: number) => `hace ${n} min`,
  timeH: (n: number) => `hace ${n} h`, timeD: (n: number) => `hace ${n} d`,
  packageReady: (v: number, f: number, c: number) =>
    `${v} palabras · ${f} frases · ${c} conceptos activados → ver paquete`,
  photoFallback: "(foto)",
  // detalle de una captura (historial clicable)
  detailLoading: "cargando…",
  detailCorrection: "Corrección", detailMeaning: "Significado",
  detailConcepts: "Conceptos", detailVocab: "Vocabulario",
  detailNotes: "Nota", detailWord: "Palabra",
  detailEmpty: "De esta captura solo quedó la microdosis — no hay más que mostrar.",
  detailPartial: "Captura antigua: se muestra lo que se guardó en su día.",
  detailFailed: "No se pudo cargar el detalle. Inténtalo de nuevo.",
  detailClose: "Cerrar",
  // sesión diaria — el arco de 15 min (tarjeta en Inicio + runner en /sesion)
  sessionPreparing: "preparando tu sesión…",
  sessionVocabLabel: "Vocabulario",
  sessionButton: (min: number, what: string) => `${min} min · ${what}`,
  sessionContinue: (done: number, total: number) => `Continuar · ${done}/${total}`,
  sessionDoneToday: "Hecho por hoy",
  sessionDoneSub: "Buen trabajo. Mañana habrá otra.",
  sessionChange: "cambiar sesión",
  sessionError: "No se pudo preparar la sesión.",
  sessionRule: "Regla",
  sessionPitfall: "Ojo (alemán)",
  sessionUnderstood: "Entendido",
  sessionReveal: "Mostrar",
  sessionGood: "bien", sessionBad: "mal",
  sessionNext: "Siguiente",
  sessionCorrect: "✓ Correcto",
  sessionSolution: "Solución:",
  sessionCheck: "Comprobar",
  sessionWrite: "escribe…",
  sessionFixIntro: "Tu frase — corrígela",
  sessionSaidWord: "¿cómo se dice?",
  sessionWriteWord: "escríbela",
  sessionOtra: "otra",
  sessionMore: "más ejercicios",
  sessionNewTraining: "nuevo entrenamiento",
  sessionRegenerating: "generando…",
  sessionSummaryExercises: (ok: number, total: number) => `${ok}/${total} ejercicios`,
  sessionSummaryVocab: (n: number) => `${n} palabras repasadas`,
  sessionSaved: "resultados guardados ✓",
  sessionToInicio: "← Inicio",
  // gramática
  gramaticaTitle: "Gramática",
  summary: (total: number, touched: number, hot: number, dom: number) =>
    `${total} capítulos · ${touched} tocados · ${hot} en caliente · ${dom} dominados`,
  yoursNow: "Lo tuyo ahora", draft: "borrador", draftLong: "borrador — sin revisar",
  chapterMissing: "Este capítulo no existe.",
  yourProblem: "Esto es lo que te pasa",
  timesCaptured: (n: number) =>
    `${n} ${n === 1 ? "vez" : "veces"} capturado — la regla de abajo explica tu problema.`,
  ruleOfThumb: "Regla de oro", germanPitfall: "⚠️ La trampa alemana",
  paradigm: "Paradigma", patternVerbs: "Verbos de este patrón", tryIt: "Para probar",
  draftEmpty: "Este capítulo nació de tus capturas y aún no tiene contenido.",
  generateBtn: "✨ Generar contenido", generating: "escribiendo el capítulo… (medio minuto)",
  generateFailed: "No se pudo generar — inténtalo otra vez.",
  exercisesBtn: "🏋️ Ejercicios interactivos", exTitle: "Ejercicios",
  exEmpty: "Este capítulo aún no tiene ejercicios.",
  exGenerate: "✨ Generar ejercicios", exGenerating: "escribiendo ejercicios… (medio minuto)",
  exGenFailed: "No se pudo generar — inténtalo otra vez.",
  exCheck: "comprobar", exNext: "siguiente →", exPlaceholder: "tu respuesta…",
  exCorrect: "✓ Correcto", exSolution: "solución:",
  exDone: (ok: number, total: number) => `${ok}/${total} correctas`,
  exMore: "✨ más ejercicios", exAgain: "otra ronda",
  chatTitle: "Dudas", chatPlaceholder: "pregunta sobre este tema…",
  chatSend: "preguntar", chatThinking: "pensando…",
  chatFailed: "No se pudo responder — inténtalo otra vez.",
  // escucha (comprensión oral)
  escuchaBtn: "🎧 Escucha", escuchaDesc: "Comprensión oral con tu vocabulario",
  escuchaTitle: "Escucha", escuchaPreparing: "preparando tu audio… (unos segundos)",
  escuchaListen: "Escucha y responde", escuchaReplay: "↻ otra vez",
  escuchaSubmit: "corregir", escuchaTranscript: "Transcripción",
  escuchaAgain: "otro audio",
  escuchaFailed: "No se pudo preparar el audio — inténtalo otra vez.",
  escuchaScore: (ok: number, total: number) => `${ok}/${total} correctas`,
  // vocabulario
  vocabularioTitle: "Vocabulario",
  dueToday: (n: number) => `${n} para repasar hoy → Practicar`,
  allReviewed: "todo repasado por hoy ✓",
  newSituationPlaceholder: "Nueva situación… (p.ej. cita con el dentista)",
  createBtn: "crear", creating: "montando…",
  createFailed: "No se pudo crear — ¿backend corriendo?",
  situationsTitle: "Situaciones", looseTitle: "Sueltas — de tus capturas",
  items: (n: number) => `${n} ${n === 1 ? "elemento" : "elementos"}`,
  seedTag: " · estándar",
  vocabEmpty: "Aún no hay vocabulario — captura algo o crea una situación arriba.",
  briefPrefix: "prepárame para",
  // importar vocabulario (CSV/TSV, sin IA)
  importEntry: "Subir material (PDF · foto · lista)",
  importTitle: "Importar vocabulario",
  importHint: "Pega o sube un CSV/TSV (estilo Anki): término y traducción. Se detecta el separador; tú confirmas las columnas antes de guardar.",
  importPastePlaceholder: "hola\thola…\ngracias\tdanke\n… o sube un archivo",
  importFileBtn: "Elegir archivo",
  importDetected: (d: string) => `separador: ${d === "\t" ? "tabulador" : d}`,
  importColTerm: "Columna del término",
  importColTranslation: "Columna de la traducción",
  importHasHeader: "La primera fila es un encabezado",
  importSituation: "Situación (opcional)",
  importSituationPlaceholder: "p. ej. en la sidrería",
  importPreviewTitle: "Vista previa",
  importCounts: (n: number, d: number) =>
    `${n} ${n === 1 ? "nueva" : "nuevas"}${d > 0 ? ` · ${d} ya en tu vocabulario` : ""}`,
  importBadgeNew: "nueva", importBadgeDup: "ya la tienes",
  importCommitBtn: (n: number) => `Importar ${n} ${n === 1 ? "palabra" : "palabras"}`,
  importing: "importando…",
  importNothingNew: "Nada nuevo que importar — todo ya está en tu vocabulario.",
  importDone: (n: number, d: number) =>
    `${n} ${n === 1 ? "palabra importada" : "palabras importadas"} en frío ✓${d > 0 ? ` · ${d} omitidas` : ""}`,
  importEmpty: "Pega o sube algo primero.",
  importFailed: "No se pudo importar — ¿está corriendo el backend?",
  importBackToVocab: "← Vocabulario",
  // subir material de estudio (documento: PDF/imagen/texto, vía análisis)
  uploadTabDoc: "Material de estudio",
  uploadTabList: "Lista (CSV/TSV)",
  uploadDocHint: "Sube un PDF, una foto o pega texto de tu material. La app detecta de qué trata y qué conceptos toca — enlaza a tus capítulos, nunca copia la explicación.",
  uploadDocPlaceholder: "Pega aquí el texto de tu material de estudio…",
  uploadAnalyzeBtn: "Analizar",
  uploadAnalyzing: "analizando…",
  uploadModeQ: "¿Qué guardamos?",
  uploadModeGrammar: "Gramática", uploadModeVocab: "Vocabulario", uploadModeBoth: "Ambos",
  uploadSuggested: "sugerido",
  uploadConceptsTitle: "Conceptos que toca",
  uploadConceptLinked: "enlazado", uploadConceptNew: "nuevo · a revisar",
  uploadBoostNote: "Estos conceptos suben a tu foco esta semana (sin contar como fallo).",
  uploadVocabTitle: "Vocabulario",
  uploadVocabCounts: (n: number, t: number) => `${n} ${n === 1 ? "nueva" : "nuevas"} de ${t}`,
  uploadCommitBtn: "Guardar",
  uploadCommitting: "guardando…",
  uploadDone: (c: number, v: number) =>
    `${c} ${c === 1 ? "concepto activado" : "conceptos activados"} · ${v} ${v === 1 ? "palabra" : "palabras"} (en frío) ✓`,
  uploadNothing: "No se reconoció nada útil — prueba con otra imagen o más texto.",
  uploadFailed: "No se pudo analizar — ¿está corriendo el backend?",
  uploadFilesPicked: (n: number) => `${n} ${n === 1 ? "archivo" : "archivos"} listo${n === 1 ? "" : "s"}`,
  shelfCrumb: "situación", keyVocab: "Vocabulario clave",
  intentPhrases: "Frases con intención", activatedGrammar: "La gramática que esto activa",
  situationMissing: "Esta situación no existe.",
  dictTitle: "Diccionario básico",
  dictAdd: "añadir", dictAdded: "en tu repaso ✓",
  // practicar — drei Kacheln: Mix (= Tages-Session), Vocabulario (SRS), Gramática (Übungen)
  practicarTitle: "Practicar",
  practicarMixTitle: "Mix — tu entrenamiento",
  practicarMixDesc: "La sesión de 20 min: vocabulario + un tema de gramática",
  practicarVocabTitle: "Vocabulario",
  practicarVocabDesc: "Repaso SRS — tus palabras y frases",
  practicarGramTitle: "Gramática",
  practicarGramDesc: "Tus fallos reales y ejercicios de tus temas flojos",
  preparingSession: "preparando sesión…",
  sessionLoadFailed: "No se pudo cargar la sesión — ¿backend corriendo?",
  nothingPending: "Nada pendiente en esta categoría ahora mismo — captura más o prueba otro modo.",
  chooseOther: "← elegir otro modo",
  sessionDone: "Sesión terminada ✓", cardsReviewed: (n: number) => `${n} tarjetas repasadas.`,
  tallyGood: "bien", tallyBad: "mal", anotherSession: "otra sesión", toInicio: "→ Inicio",
  howToSay: "¿Cómo se dice?", howToSayPhrase: "¿Cómo se dice esta frase?",
  fixYourSentence: "Corrige tu frase", conjugate: "Conjuga",
  showBtn: "mostrar", nextBtn: "siguiente",
  // login
  loginHello: "Hola 👋", loginSub: "Entra para seguir aprendiendo.",
  loginUser: "usuario", loginPass: "contraseña", loginBtn: "Entrar", loggingIn: "entrando…",
  loginWrong: "Usuario o contraseña incorrectos.", loginFailed: "Algo falló.",
  loginNoBackend: "No hay conexión con el backend.",
  // nivel
  nivelTitle: "Test de nivel",
  nivelHint: "~3 minutos · si no lo sabes, elige cualquiera — así sabemos dónde empezar.",
  evaluating: "evaluando…", yourLevel: "Tu nivel aproximado",
  correctOf: (c: number, t: number) => `${c} de ${t} correctas.`,
  weakIntro: "Tus primeros puntos flojos — ya están en tu Gramática:",
  startBtn: "Empezar →",
  // perfil
  perfilTitle: "Perfil", logoutBtn: "Salir", levelPrefix: "nivel ~", adminTag: "admin",
  usersTitle: "Usuarios", testPending: "test pendiente", passwordBtn: "contraseña",
  newUserTitle: "Nuevo usuario",
  userPlaceholder: "usuario (solo letras/números)", namePlaceholder: "nombre visible",
  passPlaceholder: "contraseña (mín. 8)",
  userCreated: (u: string) => `Usuario '${u}' creado ✓`,
  passChanged: (u: string) => `Contraseña de '${u}' cambiada ✓`,
  newPassPrompt: (u: string) => `Nueva contraseña para '${u}' (mín. 8):`,
  somethingFailed: "Algo falló.",
  // estados
  stateLabels: {
    sin_ver: "sin ver", visto: "visto", flojo: "flojo",
    aprendiendo: "aprendiendo", dominado: "dominado",
  } as Record<string, string>,
  persons: ["yo", "tu", "el", "nosotros", "vosotros", "ellos"],
  personLabels: {
    yo: "yo", tu: "tú", el: "él/ella", nosotros: "nosotros",
    vosotros: "vosotros", ellos: "ellos/ellas",
  } as Record<string, string>,
  // inicio: Hablar-Feedback (ES-only, per LANG gegated)
  inicioHablar: "Tu feedback de Hablar",
  inicioHablarEmpty: "Contesta a las preguntas del bot de Telegram y verás tu feedback aquí.",
  // capturar: Fallback, wenn der Kamera-Dialog nicht automatisch aufgeht (Deep-Link)
  cameraFallbackHint: "¿No se abrió la cámara? Toca 📷 Cámara.",
  // importar: ehrliche Fehlerzustände
  importUnreadable: "No se pudo leer el archivo — ¿seguro que es CSV/TSV?",
  importNoRows: "No se reconoció ninguna fila — revisa el archivo o el separador.",
  // Fehler + Retry
  retryBtn: "reintentar",
  nivelFailed: "No se pudo cargar el test — ¿backend corriendo?",
  // diccionari: Topic-Zähler ohne irreführenden Haken
  dictTopicCount: (a: number, t: number) => `${a}/${t} añadidas`,
  // sueltas: Suche + Kappung
  looseSearch: "buscar…",
  looseShowAll: (n: number) => `mostrar todas (${n})`,
};

const ca: typeof es = {
  appName: "llengua",
  navInicio: "Inici", navGramatica: "Gramàtica", navVocabulario: "Vocabulari",
  navPracticar: "Practicar", navCapturar: "Capturar", navHablar: "Parlar",
  // hablar — rendert auf ca nie (Tab ES-only gegated); TODO(ca-Durchgang)
  hablarTitle: "Parlar",
  hablarEmpty: "Encara no hi ha sessions.",
  hablarOpenChunks: "chunks oberts",
  hablarErrors14d: "errors · 14 dies",
  hablarSessionErrors: (n: number) => `${n} ${n === 1 ? "error" : "errors"}`,
  hablarSessionChunks: (n: number) => `${n} ${n === 1 ? "chunk" : "chunks"}`,
  hablarRecurrence: (n: number) => `${n}a vegada en 14 dies`,
  hablarTranscript: "Transcripció",
  hablarCorrected: "Versió corregida",
  hablarErrorsTitle: "Errors",
  hablarChunksTitle: "Chunks",
  hablarAudioMissing: "Àudio no disponible.",
  hablarLegend: "vermell = error · ambre = paraula alemanya · puntejat = poca confiança",
  errorTypeLabels: {
    subjuntivo: "subjuntiu", ser_estar: "ser/estar",
    indefinido_imperfecto: "indefinit/imperfet", perifrasis: "perífrasi",
    preposicion: "preposició", concordancia: "concordança", genero: "gènere",
    lexico: "lèxic", orden_palabras: "ordre de paraules", germanismo: "germanisme",
    registro: "registre", conector: "connector",
  } as Record<string, string>,
  chunkStatusLabels: {
    open: "obert", activated: "activat", dropped: "caducat",
  } as Record<string, string>,
  inicioTitle: "Inici",
  greetMorning: "Bon dia", greetAfternoon: "Bona tarda", greetEvening: "Bona nit",
  inicioGrammar: "La teva gramàtica ara", inicioVocab: "Posa a prova el teu vocabulari",
  inicioListen: "Comprensió oral",
  vocabTestCta: "Practica el teu vocabulari",
  emptyGrammar: "Encara no hi ha temes — captura alguna cosa i apareixeran.",
  bandHot: "En calent", bandReview: "Per repassar", bandPrep: "Prep per avui",
  emptyHot: "Els conceptes acabats de promoure apareixeran aquí.",
  emptyReview: "El teu repàs del dia, quan hi hagi vocabulari per repassar.",
  emptyPrep: "Preparació per a les teves cites d'avui.",
  errorsCaptured: (n) => `${n} ${n === 1 ? "error capturat" : "errors capturats"}`,
  wordsToReview: (n) => `${n} ${n === 1 ? "paraula" : "paraules"} per repassar`,
  captureHint: "Captura alguna cosa del teu dia amb el botó",
  loadFailed: "(no s'ha pogut carregar — el backend funciona?)",
  loading: "carregant…",
  capturarTitle: "Capturar",
  placeholderDefault: "El que has dit, el que has vist, el que no has entès…",
  placeholderVoice: "La veu arriba aviat — de moment, escriu el que has sentit…",
  voiceBtn: "Veu", voiceStop: "Parar", recording: "gravant…",
  audioReady: "Àudio a punt — es transcriu en capturar", audioRemove: "Treure l'àudio",
  micDenied: "Sense accés al micròfon — revisa els permisos.", heard: "he sentit:",
  placeholderPhotoContext: "Context opcional per a la foto…",
  photoReady: "Foto a punt per analitzar", photoRemove: "Treure la foto",
  cameraBtn: "Càmera", captureBtn: "Capturar", analyzing: "analitzant…",
  captureFailed: (e) => `No s'ha pogut capturar (${e}). El backend funciona?`,
  modeLabels: { check: "revisat", decode: "desxifrat", brief: "preparació", listen: "escoltat", word: "paraula" },
  wordAdded: "→ al teu vocabulari ✓", wordKnown: "ja al teu vocabulari",
  correctMark: "✓ Correcte.",
  savedSilently: "desat en silenci ✓", seeLesson: "→ veure la lliçó",
  historyTitle: "Últimes captures",
  timeNow: "ara", timeMin: (n) => `fa ${n} min`,
  timeH: (n) => `fa ${n} h`, timeD: (n) => `fa ${n} d`,
  packageReady: (v, f, c) => `${v} paraules · ${f} frases · ${c} conceptes activats → veure el paquet`,
  photoFallback: "(foto)",
  // TODO(ca-Durchgang): nur damit der Typ passt — im eigenen llengua-Durchgang gegenlesen.
  detailLoading: "carregant…",
  detailCorrection: "Correcció", detailMeaning: "Significat",
  detailConcepts: "Conceptes", detailVocab: "Vocabulari",
  detailNotes: "Nota", detailWord: "Paraula",
  detailEmpty: "D'aquesta captura només va quedar la microdosi — no hi ha res més a mostrar.",
  detailPartial: "Captura antiga: es mostra el que es va desar aleshores.",
  detailFailed: "No s'ha pogut carregar el detall. Torna-ho a provar.",
  detailClose: "Tancar",
  // TODO(ca-Durchgang): nur damit der Typ passt — im eigenen llengua-Durchgang gegenlesen.
  sessionPreparing: "preparant la teva sessió…",
  sessionVocabLabel: "Vocabulari",
  sessionButton: (min, what) => `${min} min · ${what}`,
  sessionContinue: (done, total) => `Continuar · ${done}/${total}`,
  sessionDoneToday: "Fet per avui",
  sessionDoneSub: "Bona feina. Demà n'hi haurà una altra.",
  sessionChange: "canviar sessió",
  sessionError: "No s'ha pogut preparar la sessió.",
  sessionRule: "Regla",
  sessionPitfall: "Compte (alemany)",
  sessionUnderstood: "Entès",
  sessionReveal: "Mostrar",
  sessionGood: "bé", sessionBad: "malament",
  sessionNext: "Següent",
  sessionCorrect: "✓ Correcte",
  sessionSolution: "Solució:",
  sessionCheck: "Comprovar",
  sessionWrite: "escriu…",
  sessionFixIntro: "La teva frase — corregeix-la",
  sessionSaidWord: "com es diu?",
  sessionWriteWord: "escriu-la",
  sessionOtra: "una altra",
  sessionMore: "més exercicis",
  sessionNewTraining: "nou entrenament",
  sessionRegenerating: "generant…",
  sessionSummaryExercises: (ok, total) => `${ok}/${total} exercicis`,
  sessionSummaryVocab: (n) => `${n} paraules repassades`,
  sessionSaved: "resultats desats ✓",
  sessionToInicio: "← Inici",
  gramaticaTitle: "Gramàtica",
  summary: (total, touched, hot, dom) =>
    `${total} capítols · ${touched} tocats · ${hot} en calent · ${dom} dominats`,
  yoursNow: "El teu ara mateix", draft: "esborrany", draftLong: "esborrany — sense revisar",
  chapterMissing: "Aquest capítol no existeix.",
  yourProblem: "Això és el que et passa",
  timesCaptured: (n) =>
    `${n} ${n === 1 ? "vegada capturada" : "vegades capturades"} — la regla de sota explica el teu problema.`,
  ruleOfThumb: "Regla d'or", germanPitfall: "⚠️ La trampa alemanya",
  paradigm: "Paradigma", patternVerbs: "Verbs d'aquest patró", tryIt: "Per provar",
  draftEmpty: "Aquest capítol va néixer de les teves captures i encara no té contingut.",
  generateBtn: "✨ Generar contingut", generating: "escrivint el capítol… (mig minut)",
  generateFailed: "No s'ha pogut generar — torna-ho a provar.",
  exercisesBtn: "🏋️ Exercicis interactius", exTitle: "Exercicis",
  exEmpty: "Aquest capítol encara no té exercicis.",
  exGenerate: "✨ Generar exercicis", exGenerating: "escrivint exercicis… (mig minut)",
  exGenFailed: "No s'ha pogut generar — torna-ho a provar.",
  exCheck: "comprovar", exNext: "següent →", exPlaceholder: "la teva resposta…",
  exCorrect: "✓ Correcte", exSolution: "solució:",
  exDone: (ok, total) => `${ok}/${total} correctes`,
  exMore: "✨ més exercicis", exAgain: "una altra ronda",
  chatTitle: "Dubtes", chatPlaceholder: "pregunta sobre aquest tema…",
  chatSend: "preguntar", chatThinking: "pensant…",
  chatFailed: "No s'ha pogut respondre — torna-ho a provar.",
  // escucha (comprensió oral)
  escuchaBtn: "🎧 Escolta", escuchaDesc: "Comprensió oral amb el teu vocabulari",
  escuchaTitle: "Escolta", escuchaPreparing: "preparant el teu àudio… (uns segons)",
  escuchaListen: "Escolta i respon", escuchaReplay: "↻ una altra vegada",
  escuchaSubmit: "corregir", escuchaTranscript: "Transcripció",
  escuchaAgain: "un altre àudio",
  escuchaFailed: "No s'ha pogut preparar l'àudio — torna-ho a provar.",
  escuchaScore: (ok, total) => `${ok}/${total} correctes`,
  vocabularioTitle: "Vocabulari",
  dueToday: (n) => `${n} per repassar avui → Practicar`,
  allReviewed: "tot repassat per avui ✓",
  newSituationPlaceholder: "Nova situació… (p. ex. cita amb el dentista)",
  createBtn: "crear", creating: "muntant…",
  createFailed: "No s'ha pogut crear — el backend funciona?",
  situationsTitle: "Situacions", looseTitle: "Soltes — de les teves captures",
  items: (n) => `${n} ${n === 1 ? "element" : "elements"}`,
  seedTag: " · estàndard",
  vocabEmpty: "Encara no hi ha vocabulari — captura alguna cosa o crea una situació a dalt.",
  briefPrefix: "prepara'm per a",
  // importar vocabulari (CSV/TSV, sense IA)
  importEntry: "Puja material (PDF · foto · llista)",
  importTitle: "Importa vocabulari",
  importHint: "Enganxa o puja un CSV/TSV (estil Anki): terme i traducció. Es detecta el separador; tu confirmes les columnes abans de desar.",
  importPastePlaceholder: "hola\thola…\ngràcies\tdanke\n… o puja un fitxer",
  importFileBtn: "Tria un fitxer",
  importDetected: (d: string) => `separador: ${d === "\t" ? "tabulador" : d}`,
  importColTerm: "Columna del terme",
  importColTranslation: "Columna de la traducció",
  importHasHeader: "La primera fila és una capçalera",
  importSituation: "Situació (opcional)",
  importSituationPlaceholder: "p. ex. a la sidreria",
  importPreviewTitle: "Vista prèvia",
  importCounts: (n: number, d: number) =>
    `${n} ${n === 1 ? "nova" : "noves"}${d > 0 ? ` · ${d} ja al teu vocabulari` : ""}`,
  importBadgeNew: "nova", importBadgeDup: "ja la tens",
  importCommitBtn: (n: number) => `Importa ${n} ${n === 1 ? "paraula" : "paraules"}`,
  importing: "important…",
  importNothingNew: "Res de nou per importar — tot ja és al teu vocabulari.",
  importDone: (n: number, d: number) =>
    `${n} ${n === 1 ? "paraula importada" : "paraules importades"} en fred ✓${d > 0 ? ` · ${d} omeses` : ""}`,
  importEmpty: "Enganxa o puja alguna cosa primer.",
  importFailed: "No s'ha pogut importar — el backend funciona?",
  importBackToVocab: "← Vocabulari",
  // pujar material d'estudi (document: PDF/imatge/text, via anàlisi)
  uploadTabDoc: "Material d'estudi",
  uploadTabList: "Llista (CSV/TSV)",
  uploadDocHint: "Puja un PDF, una foto o enganxa text del teu material. L'app detecta de què va i quins conceptes toca — enllaça als teus capítols, mai copia l'explicació.",
  uploadDocPlaceholder: "Enganxa aquí el text del teu material d'estudi…",
  uploadAnalyzeBtn: "Analitza",
  uploadAnalyzing: "analitzant…",
  uploadModeQ: "Què desem?",
  uploadModeGrammar: "Gramàtica", uploadModeVocab: "Vocabulari", uploadModeBoth: "Tots dos",
  uploadSuggested: "suggerit",
  uploadConceptsTitle: "Conceptes que toca",
  uploadConceptLinked: "enllaçat", uploadConceptNew: "nou · a revisar",
  uploadBoostNote: "Aquests conceptes pugen al teu focus aquesta setmana (sense comptar com a error).",
  uploadVocabTitle: "Vocabulari",
  uploadVocabCounts: (n: number, t: number) => `${n} ${n === 1 ? "nova" : "noves"} de ${t}`,
  uploadCommitBtn: "Desa",
  uploadCommitting: "desant…",
  uploadDone: (c: number, v: number) =>
    `${c} ${c === 1 ? "concepte activat" : "conceptes activats"} · ${v} ${v === 1 ? "paraula" : "paraules"} (en fred) ✓`,
  uploadNothing: "No s'ha reconegut res útil — prova amb una altra imatge o més text.",
  uploadFailed: "No s'ha pogut analitzar — el backend funciona?",
  uploadFilesPicked: (n: number) => `${n} ${n === 1 ? "fitxer" : "fitxers"} a punt`,
  shelfCrumb: "situació", keyVocab: "Vocabulari clau",
  intentPhrases: "Frases amb intenció", activatedGrammar: "La gramàtica que això activa",
  situationMissing: "Aquesta situació no existeix.",
  dictTitle: "Diccionari bàsic",
  dictAdd: "afegir", dictAdded: "al teu repàs ✓",
  practicarTitle: "Practicar",
  practicarMixTitle: "Mix — el teu entrenament",
  practicarMixDesc: "La sessió de 20 min: vocabulari + un tema de gramàtica",
  practicarVocabTitle: "Vocabulari",
  practicarVocabDesc: "Repàs SRS — les teves paraules i frases",
  practicarGramTitle: "Gramàtica",
  practicarGramDesc: "Els teus errors reals i exercicis dels temes fluixos",
  preparingSession: "preparant la sessió…",
  sessionLoadFailed: "No s'ha pogut carregar la sessió — el backend funciona?",
  nothingPending: "Res pendent en aquesta categoria ara mateix — captura més o prova un altre mode.",
  chooseOther: "← triar un altre mode",
  sessionDone: "Sessió acabada ✓", cardsReviewed: (n) => `${n} targetes repassades.`,
  tallyGood: "bé", tallyBad: "malament", anotherSession: "una altra sessió", toInicio: "→ Inici",
  howToSay: "Com es diu?", howToSayPhrase: "Com es diu aquesta frase?",
  fixYourSentence: "Corregeix la teva frase", conjugate: "Conjuga",
  showBtn: "mostrar", nextBtn: "següent",
  loginHello: "Hola 👋", loginSub: "Entra per continuar aprenent.",
  loginUser: "usuari", loginPass: "contrasenya", loginBtn: "Entrar", loggingIn: "entrant…",
  loginWrong: "Usuari o contrasenya incorrectes.", loginFailed: "Alguna cosa ha fallat.",
  loginNoBackend: "No hi ha connexió amb el backend.",
  nivelTitle: "Test de nivell",
  nivelHint: "~3 minuts · si no ho saps, tria qualsevol — així sabem on començar.",
  evaluating: "avaluant…", yourLevel: "El teu nivell aproximat",
  correctOf: (c, t) => `${c} de ${t} correctes.`,
  weakIntro: "Els teus primers punts fluixos — ja són a la teva Gramàtica:",
  startBtn: "Començar →",
  perfilTitle: "Perfil", logoutBtn: "Sortir", levelPrefix: "nivell ~", adminTag: "admin",
  usersTitle: "Usuaris", testPending: "test pendent", passwordBtn: "contrasenya",
  newUserTitle: "Nou usuari",
  userPlaceholder: "usuari (només lletres/números)", namePlaceholder: "nom visible",
  passPlaceholder: "contrasenya (mín. 8)",
  userCreated: (u) => `Usuari '${u}' creat ✓`,
  passChanged: (u) => `Contrasenya de '${u}' canviada ✓`,
  newPassPrompt: (u) => `Nova contrasenya per a '${u}' (mín. 8):`,
  somethingFailed: "Alguna cosa ha fallat.",
  stateLabels: {
    sin_ver: "per veure", visto: "vist", flojo: "fluix",
    aprendiendo: "aprenent", dominado: "dominat",
  },
  persons: ["jo", "tu", "ell", "nosaltres", "vosaltres", "ells"],
  personLabels: {
    jo: "jo", tu: "tu", ell: "ell/ella", nosaltres: "nosaltres",
    vosaltres: "vosaltres", ells: "ells/elles",
  },
  // TODO(ca-Durchgang): nur damit der Typ passt — im eigenen llengua-Durchgang gegenlesen.
  inicioHablar: "El teu feedback de Parlar",
  inicioHablarEmpty: "Contesta les preguntes del bot de Telegram i veuràs el teu feedback aquí.",
  cameraFallbackHint: "No s'ha obert la càmera? Toca 📷 Càmera.",
  importUnreadable: "No s'ha pogut llegir el fitxer — segur que és CSV/TSV?",
  importNoRows: "No s'ha reconegut cap fila — revisa el fitxer o el separador.",
  retryBtn: "torna-ho a provar",
  nivelFailed: "No s'ha pogut carregar el test — el backend funciona?",
  dictTopicCount: (a, t) => `${a}/${t} afegides`,
  looseSearch: "cerca…",
  looseShowAll: (n) => `mostra-les totes (${n})`,
};

export const S = LANG === "ca" ? ca : es;
